name: GitHub Pages

on:
  push:
    branches:
      - main  # Change if your main branch is named differently

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Build and Deploy
      run: |
        npm install
        
        # Execute your docker-compose command here
        docker-compose up -d
        
        # Add any other necessary commands to build your page
        # Example: npm run build
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUBTOKEN }}
        publish_dir: ./app  # Path to the output directory of your Docker component or generated page


