name: Ejemplo de GitHub Actions con Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2

    - name: Configurar Docker
      uses: docker/setup-docker@v2

    - name: Construir imagen de Docker
      run: docker build -t mi-componente .

    - name: Ejecutar componente de Docker
      run: docker run mi-componente
